### ISSUE TITLE
Direct scroll to letter in Write page

### ISSUE THREAD

**Issue by assiaoua** [panterch/dearswitzerland#31]
Preferably with no "jump" in scrolling as it may confuse the user.

**Comment by panterch** [comment]
@assiaoua 

- will the "Write" page still be the homepage? 
- Could you send me a screenshot of the area where we should exaclty scroll to?

**Comment by assiaoua** [comment]
- yes write will still be homepage

- no need to scroll, landing at the top of the page would be ideal :)

- I also added a X on the screenshot to indicate that we still need some sort of text there to present our project in a sentence or two

<img width="1280" alt="Screenshot 2020-04-14 at 15 09 51" src="https://user-images.githubusercontent.com/52460448/79228647-173d2780-7e62-11ea-8d88-c5e9c8bdf49b.png">

**Comment by panterch** [comment]
Ah so your ticket means that I should remove the automatic scroll on click of the "Start writing" button?

**Comment by assiaoua** [comment]
yup! the others team members it may be confusing for a first user
