### ISSUE TITLE
Template problem

### ISSUE THREAD

**Issue by assiaoua** [panterch/dearswitzerland#33]
Letters which were submitted with the template only show the template front page in the Letters tab

**Comment by panterch** [comment]
@assiaoua I don't understand this 100%. Could you give me the URL or a sample or describe a bit more how to reproduce?

**Comment by assiaoua** [comment]
I will take a screenshot of what I mean when the letters page is back

**Comment by assiaoua** [comment]
Actually I meant that we see the template and not the letter once we upload it on the Letter page.
But I just realised there's the upload button on the review page to be able to change the letter to our test (e.g. remove the template's first page), so maybe it is not required after all!

<img width="1280" alt="Screenshot 2020-04-14 at 15 47 51" src="https://user-images.githubusercontent.com/52460448/79232140-6d609980-7e67-11ea-8cce-0ecc0c380b94.png">

**Comment by panterch** [comment]
Yes that would be the idea ;-) Actually I don't think many people will really send / upload you their handwritten letter including the template page. And it would be quite difficult to detect it in scans and remove it.
