### ISSUE TITLE
Add facebook and Linkedin page in the footer

### ISSUE THREAD

**Issue by assiaoua** [panterch/dearswitzerland#37]
Only instagram for now

**Comment by panterch** [comment]
@assiaoua I would need a design or the icons for it and the links of the fb and linkedin page

**Comment by assiaoua** [comment]
Links 
https://www.facebook.com/Dear-Switzerland-103540081329743/?modal=admin_todo_tour
linkedin.com/company/dearswitzerland

I will ask Leana for the icons and update this issue whenever I receive them!
