### ISSUE TITLE
Swiss abroad / Other connection to Switzerland

### ISSUE THREAD

**Issue by assiaoua** [panterch/dearswitzerland#42]
Could we add “Swiss Abroad” and/or “Other Connection to Switzerland” to the Canton dropdown?
Let’s please add 2 :
			**Swiss Citizen Abroad**
			**Other Connection to Switzerland**

(I will handle the translations once the new keys are in)

**Comment by panterch** [comment]
Hi @assiaoua - here are two new locale keys for this: https://github.com/panterch/dearswitzerland/commit/1af54e22f07d61fbc5d38783c3a478c377c7dc14#diff-37c9b835927e3c363588f172de9bb6fa
